# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ROBUSTGARCHloss_RCPP <- function(theta, r, sigma2) {
    .Call(`_RobGARCHBoot_ROBUSTGARCHloss_RCPP`, theta, r, sigma2)
}

grid_RCPP <- function(y, sigmaR) {
    .Call(`_RobGARCHBoot_grid_RCPP`, y, sigmaR)
}

resBoot <- function(coeff, r, S, k) {
    .Call(`_RobGARCHBoot_resBoot`, coeff, r, S, k)
}

retBoot <- function(coeff, S, e, k) {
    .Call(`_RobGARCHBoot_retBoot`, coeff, S, e, k)
}

sigma2Boot <- function(coeff, e, S, r, k) {
    .Call(`_RobGARCHBoot_sigma2Boot`, coeff, e, S, r, k)
}

foreBoot <- function(coeff, e, e2, h, r, ahead, k) {
    .Call(`_RobGARCHBoot_foreBoot`, coeff, e, e2, h, r, ahead, k)
}

