# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @noRd
ROBUSTGARCHloss_RCPP <- function(theta, r, sigma2) {
    .Call('_RobGARCHBoot_ROBUSTGARCHloss_RCPP', PACKAGE = 'RobGARCHBoot', theta, r, sigma2)
}

#' @noRd
#' @useDynLib RobGARCHBoot
grid_RCPP <- function(y, sigmaR) {
    .Call('_RobGARCHBoot_grid_RCPP', PACKAGE = 'RobGARCHBoot', y, sigmaR)
}

#' @noRd
#' @useDynLib RobGARCHBoot
resBoot <- function(coeff, r, S, k) {
    .Call('_RobGARCHBoot_resBoot', PACKAGE = 'RobGARCHBoot', coeff, r, S, k)
}

#' @noRd
#' @useDynLib RobGARCHBoot
retBoot <- function(coeff, S, e, k) {
    .Call('_RobGARCHBoot_retBoot', PACKAGE = 'RobGARCHBoot', coeff, S, e, k)
}

#' @noRd
#' @useDynLib RobGARCHBoot
sigma2Boot <- function(coeff, e, S, r, k) {
    .Call('_RobGARCHBoot_sigma2Boot', PACKAGE = 'RobGARCHBoot', coeff, e, S, r, k)
}

#' @noRd
#' @useDynLib RobGARCHBoot
foreBoot <- function(coeff, e, e2, h, r, ahead, k) {
    .Call('_RobGARCHBoot_foreBoot', PACKAGE = 'RobGARCHBoot', coeff, e, e2, h, r, ahead, k)
}

#' @noRd
#' @useDynLib RobGARCHBoot
gridcDCC <- function(Qb, s, sigma) {
    .Call('_RobGARCHBoot_gridcDCC', PACKAGE = 'RobGARCHBoot', Qb, s, sigma)
}

#' @export
#' @noRd
loglik_cDCC <- function(par, Qb, s, sigma) {
    .Call('_RobGARCHBoot_loglik_cDCC', PACKAGE = 'RobGARCHBoot', par, Qb, s, sigma)
}

#' @noRd
cor_cDCC <- function(par, Qb, s) {
    .Call('_RobGARCHBoot_cor_cDCC', PACKAGE = 'RobGARCHBoot', par, Qb, s)
}

